[tool.poetry]
name = "gym-grid-world-tutorial"
version = "0.1.0"
description = ""
authors = ["Manuel Yguel <manuel.yguel@strataggem.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
